version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.1.0
  aws-ecs: circleci/aws-ecs@0.0.8
  slack: circleci/slack@3.4.1
jobs:
  slack-notify:
    docker:
      - image: circleci/python
    steps:
      - slack/status:
          channel: 'チーム-開発リリース'
          success_message: ':circleci-pass: $CIRCLE_BRANCH のデプロイが完了しました\n:github_octocat: User：$CIRCLE_USERNAME'
          failure_message: ':circleci-fail: $CIRCLE_BRANCH のデプロイが失敗しました\n:github_octocat: User：$CIRCLE_USERNAME'
          webhook: SLACK_WEBHOOK
      - run: exit 0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: 'seed-test'
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: 'demo-run-task-definition'
          cluster-name: 'demo-cluster'
          service-name: 'demo-service'
          container-image-name-updates: "container=demo-kyamanak,tag=${CIRCLE_SHA1}"
      - slack-notify
